### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by wyz22966** [lewandofskee/DiAD#17]
(1)MVTec-AD数据集在'./training/MVTec-AD/mvtec_anomaly_detection/'，但finetune_autoencoder.py 中 data_path='./data/mvtecad'，运行过程中会显示对象为空报错。我把它改为data_path='./training/MVTec-AD/mvtec_anomaly_detection/'就可以运行了。
(2)请问代码运行的轮数在哪里修改

**Comment by lewandofskee** [comment]
(1) Yes, data_path is your mvtec dataset path.
(2) You can add max_epochs parameter in pl.Trainer to set specific training epoch.
e.g. trainer = pl.Trainer(gpus=1, max_epochs=1000, precision=32,....)

**Comment by wyz22966** [comment]
thank you very much

**Comment by wyz22966** [comment]
你好，前面几个步骤都做完了，现在在运行train.py，train.py里data_path='/root/autodl-tmp/mvtecad'，所以我创建了一个一样的路径来放置数据集，但是报错了。
Validation sanity check: 0it [00:00, ?it/s]/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:440: UserWarning: Your `val_dataloader` has `shuffle=True`,it is strongly recommended that you turn this off for val/test/predict dataloaders.
  rank_zero_warn(
Validation sanity check:   0%|                                                                                                                                                                                | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 50, in <module>
    trainer.fit(model, train_dataloaders=train_dataloader, val_dataloaders=test_dataloader)
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in fit
    self._call_and_handle_interrupt(
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1193, in _run
    self._dispatch()
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1272, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1282, in run_stage
    return self._run_train()
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1304, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1368, in _run_sanity_check
    self._evaluation_loop.run()
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 109, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 140, in run
    self.on_run_start(*args, **kwargs)
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 87, in on_run_start
    self._dataloader_iter = _update_dataloader_iter(data_fetcher, self.batch_progress.current.ready)
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py", line 121, in _update_dataloader_iter
    dataloader_iter = enumerate(data_fetcher, batch_idx)
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 199, in __iter__
    self.prefetching(self.prefetch_batches)
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 258, in prefetching
    self._fetch_next_batch()
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 300, in _fetch_next_batch
    batch = next(self.dataloader_iter)
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/test/anaconda3/envs/diad/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/test/wangpan/DiAD/mvtecad_dataloader.py", line 66, in __getitem__
    source = cv2.cvtColor(source, 4)
cv2.error: OpenCV(4.3.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
